[package]
name = "pique"
version = "0.1.0"
authors = ["Pebaz <pebazium@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "pq"
path = "src/main.rs"

[dependencies]
json = "0.12.1"
